name: Test Numpy Loss of Precision

on: [push, pull_request]

jobs:
  tests:
    name: Numpy=${{ matrix.numpy-version }}, OS=${{ matrix.os }}, Python=${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        numpy-version: ["<1.24", ">=1.24"]
        os: [ubuntu-20.04, ubuntu-22.04, windows-2019, windows-2022, macOS-11, macOS-12]
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install "numpy${{ matrix.numpy-version }}" pytest threadpoolctl

      - name: Environment information
        run: |
          python -c "import sys; print(sys.version)"
          python -c "import numpy; print(numpy.__version__);"

      - name: Numpy runtime information
        if: contains(matrix.numpy-version, '>=1.24')
        run: |
          python -c "import numpy; print(numpy.show_runtime())"

      - name: Run Tests
        run: |
          pytest test.py
