name: Test Numpy Loss of Precision

on: [push, pull_request]

jobs:
  Unit Test:
    name: OS=${{ matrix.os }}, Python=${{ matrix.python-version }}, Numpy=${{ matrix.numpy-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, windows-2019, windows-2022, macOS-11, macOS-12]
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        numpy-version: ["<1.24", ">=1.24"]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install "numpy${{ matrix.numpy-version }}" pytest

      - name: Environment information
        run: |
          python -c "import sys; print(sys.version)"
          python -c "import numpy; print(numpy.__version__);"
          python -c "import numpy; print(numpy.show_runtime())"

      - name: Run Tests
        run: |
          pytest test.py
